main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('makeup/', views.makeup_index, name='index'),
  path('makeup/<int:makeup_id>/', views.makeup_detail, name='detail'),
  path('makeup/create/', views.MakeupCreate.as_view(), name='makeup_create'),
  path('makeup/<int:pk>/update/', views.MakeupUpdate.as_view(), name='makeup_update'),
  path('makeup/<int:pk>/delete/', views.MakeupDelete.as_view(), name='makeup_delete'),
  path('makeup/<int:makeup_id>/add_review/', views.add_review, name='add_review'),
  path('makeup/<int:makeup_id>/add_photo/', views.add_photo, name='add_photo'),
  path('makeup/<int:makeup_id>/assoc_dupe/<int:dupe_id>/', views.assoc_dupe, name='assoc_dupe'),
  path('makeup/<int:makeup_id>/unassoc_dupe/<int:dupe_id>/', views.unassoc_dupe, name='unassoc_dupe'),
  path('dupes/', views.DupeList.as_view(), name='dupes_index'),
  path('dupes/<int:pk>/', views.DupeDetail.as_view(), name='dupes_detail'),
  path('dupes/create/', views.DupeCreate.as_view(), name='dupes_create'),
  path('dupes/<int:pk>/update/', views.DupeUpdate.as_view(), name='dupes_update'),
  path('dupes/<int:pk>/delete/', views.DupeDelete.as_view(), name='dupes_delete'),
  path('accounts/signup/', views.signup, name='signup'),
]

makeupcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Dupe(models.Model):
  name = models.CharField(max_length=50)
  price = models.IntegerField()

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('dupes_detail', kwargs={'pk': self.id})

class Makeup(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    description =  models.TextField(max_length=300)
    price = models.IntegerField()
    dupes = models.ManyToManyField(Dupe)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    # Add this method
    def get_absolute_url(self):
        return reverse('detail', kwargs={'makeup_id': self.id})


RATINGS = (
    ('0', '☆☆☆☆☆'),
    ('1', '★☆☆☆☆'),
    ('2', '★★☆☆☆'),
    ('3', '★★★☆☆'),
    ('4', '★★★★☆'),
    ('5', '★★★★★')
)

class Reviews(models.Model):
    date = models.DateField('review date')
    review = models.CharField(max_length=100)
    rating = models.CharField(max_length=6 , choices=RATINGS, default=RATINGS[0][0])

    # Create a makeup_id FK
    makeup = models.ForeignKey(Makeup, on_delete=models.CASCADE)

    def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_rating_display()} on {self.date}"

     # change the default sort
    class Meta:
        ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    makeup = models.ForeignKey(Makeup, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for makeup_id: {self.cat_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Reviews

class ReviewsForm(ModelForm):
  class Meta:
    model = Reviews
    fields = ['date', 'review', 'rating']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from .models import Makeup, Dupe, Photo
from .forms import ReviewsForm
import uuid
import boto3

S3_BASE_URL = 'https://s3.ca-central-1.amazonaws.com/'
BUCKET = 'catcollec1'

class MakeupCreate(LoginRequiredMixin,CreateView):
  model = Makeup
  fields = '__all__'

  # This inherited method is called when a
  # valid cat form is being submitted
  def form_valid(self, form):
    # Assign the logged in user (self.request.user)
    form.instance.user = self.request.user  # form.instance is the cat
    # Let the CreateView do its job as usual
    return super().form_valid(form)

class MakeupUpdate(LoginRequiredMixin,UpdateView):
  model = Makeup
  fields = '__all__'

class MakeupDelete(LoginRequiredMixin,DeleteView):
  model = Makeup
  success_url = '/makeup/'

# Define the home view
def home(request):
  return HttpResponse('<h1>Hello</h1>')

def about(request):
  return render(request, 'about.html')

@login_required
def makeup_index(request):
  makeups = Makeup.objects.filter(user=request.user)
  return render(request, 'makeup/index.html', { 'makeups': makeups })

@login_required
def makeup_detail(request, makeup_id):
  makeup = Makeup.objects.get(id=makeup_id)
  dupes_makeup_doesnt_have = Dupe.objects.exclude(id__in = makeup.dupes.all().values_list('id'))
  reviews_form = ReviewsForm()
  return render(request, 'makeup/detail.html', { 'makeup': makeup, 'reviews_form':reviews_form, 'dupes': dupes_makeup_doesnt_have })

@login_required
def add_review(request, makeup_id):
  form = ReviewsForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_review = form.save(commit=False)
    new_review.makeup_id = makeup_id
    new_review.save()
  return redirect('detail', makeup_id=makeup_id)

@login_required
def assoc_dupe(request, makeup_id, dupe_id):
  Makeup.objects.get(id=makeup_id).dupes.add(dupe_id)
  return redirect('detail', makeup_id=makeup_id)

@login_required
def unassoc_dupe(request, makeup_id, dupe_id):
  Makeup.objects.get(id=makeup_id).dupes.remove(dupe_id)
  return redirect('detail', makeup_id=makeup_id)

class DupeList(LoginRequiredMixin,ListView):
  model = Dupe

class DupeDetail(LoginRequiredMixin,DetailView):
  model = Dupe

class DupeCreate(LoginRequiredMixin,CreateView):
  model = Dupe
  fields = '__all__'

class DupeUpdate(LoginRequiredMixin,UpdateView):
  model = Dupe
  fields = ['name', 'price']

class DupeDelete(LoginRequiredMixin,DeleteView):
  model = Dupe
  success_url = '/dupes/'

@login_required
def add_photo(request, makeup_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to cat_id or cat (if you have a cat object)
            photo = Photo(url=url, makeup_id=makeup_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', makeup_id=makeup_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Makeup Collector</h1>
<hr />
<p>Hire the Makeup Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Makeup Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;MakeupCollector</a></li>
        </ul>
        <ul class="right">
        {% if user.is_authenticated %}
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'dupes_create' %}">Add a Dupe</a></li>
          <li><a href="{% url 'dupes_index' %}">View All Dupes</a></li>
          <li><a href="{% url 'makeup_create' %}">Add a Makeup Product</a></li>
          <li><a href="{% url 'index' %}">View All My Makeup Products</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Makeup Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/main_app/dupe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Dupe</h1>

  <h4>Are you sure you want to delete <span class="pink-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn" style="background-color:#e91e63 ">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dupe_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Dupe Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dupe.name }}</span>
        <p>Color: {{ dupe.price }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'dupes_update' dupe.id %}">Edit Dupe</a>
        <a href="{% url 'dupes_delete' dupe.id %}">Delete Dupe</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/dupe_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="pink-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Dupe</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn" style="background-color:#e91e63 ">
  </form>
{% endblock %}

main_app/templates/main_app/dupe_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Dupe List</h1>

{% for dupe in dupe_list %}
  <a href="{% url 'dupes_detail' dupe.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ dupe.name }}</span>
            <p>Color: {{ dupe.price }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/makeup_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Makeup Product</h1>

  <h4>Are you sure you want to delete this product: <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn" style="background-color:#e91e63 ">
    <a href="{% url 'detail' makeup.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/makeup_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
        <h1>Edit This Product: <span class="pink-text">{{object.name}}</span></h1>
    {% else %}
        <h1>Add Makeup Product</h1>
    {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn" style="background-color:#e91e63 ">
  </form>
{% endblock %}

main_app/templates/makeup/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Makeup Product Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ makeup.name }}</span>
        <p>Category: {{ makeup.category }}</p>
        <p>Description: {{ makeup.description }}</p>
        <p>Price: {{ makeup.price }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'makeup_update' makeup.id %}">Edit Product</a>
        <a href="{% url 'makeup_delete' makeup.id %}">Delete Product</a>
      </div>
    </div>
    {% for photo in makeup.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel pink-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' makeup.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" style="background-color:#e91e63" value="Upload Photo">
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_review' makeup.id %}" method="post">
      {% csrf_token %}
      {{ reviews_form.as_p }}
      <input type="submit" class="btn"  style="background-color:#e91e63" value="Add A Review">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Review</th><th>Rating</th></tr>
      </thead>
      <tbody>
        {% for review in makeup.reviews_set.all %}
          <tr>
            <td>{{review.date}}</td>
            <td>{{review.review}}</td>
            <td>{{review.get_rating_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ makeup.name }}'s Dupes</h3>
    {% if makeup.dupes.count %}
      {% for dupe in makeup.dupes.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              $<span style="color:#e91e63">{{ dupe.price }}</span> - {{ dupe.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Dupes :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Dupes</h3>
    {% if dupes.count %}
      {% for dupe in dupes.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              $<span style="color:#e91e63">{{ dupe.price }}</span> - {{ dupe.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_dupe' makeup.id dupe.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add Dupe</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{makeup.name}} Already Has All The Dupe Available</h5>
    {% endif %}
  </div>
</div>
<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  // add additional JS to initialize select below
  var selectEl = document.getElementById('id_rating');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/makeup/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Makeup List</h1>

{% for makeup in makeups %}
  <div class="card">
    <a href="{% url 'detail' makeup.id %}">
    <div class="card-content">
      <span class="card-title">{{ makeup.name }}</span>
      <p>Category: {{ makeup.category }}</p>
      <p>Description: {{ makeup.description }}</p>
      <p>Price: {{ makeup.price }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}